// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASdhC_reDhl6TOt6yN2oTTwWwmZ8kfDFU',
    appId: '1:945032935281:web:ba5cae18d446c97eede8d0',
    messagingSenderId: '945032935281',
    projectId: 'evpanet-f3ea6',
    authDomain: 'evpanet-f3ea6.firebaseapp.com',
    databaseURL: 'https://evpanet-f3ea6.firebaseio.com',
    storageBucket: 'evpanet-f3ea6.appspot.com',
    measurementId: 'G-6LPX0K2HC4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzqNId3XwLJN1BIdGcst6tZYGpFUpFn8o',
    appId: '1:945032935281:android:8c49723dd6a7bcf5ede8d0',
    messagingSenderId: '945032935281',
    projectId: 'evpanet-f3ea6',
    databaseURL: 'https://evpanet-f3ea6.firebaseio.com',
    storageBucket: 'evpanet-f3ea6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTYbV8-rOYqrT2L6w_1WPdaVOllZtFua4',
    appId: '1:945032935281:ios:8eb806e97444bd3dede8d0',
    messagingSenderId: '945032935281',
    projectId: 'evpanet-f3ea6',
    databaseURL: 'https://evpanet-f3ea6.firebaseio.com',
    storageBucket: 'evpanet-f3ea6.appspot.com',
    iosBundleId: 'com.example.myevpanet4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTYbV8-rOYqrT2L6w_1WPdaVOllZtFua4',
    appId: '1:945032935281:ios:68ca9c77593eeb04ede8d0',
    messagingSenderId: '945032935281',
    projectId: 'evpanet-f3ea6',
    databaseURL: 'https://evpanet-f3ea6.firebaseio.com',
    storageBucket: 'evpanet-f3ea6.appspot.com',
    iosBundleId: 'com.example.myevpanet4.RunnerTests',
  );
}
